version: '3'

services:
  mongodb:
    image: mongo
    container_name: newHackers_mongo
    env_file: .env
    volumes:
     - ./.docker/mongodb/data/db/:/data/db/
    ports:
    - ${MONGODB_PORT}:${MONGODB_PORT}
    restart: always

  mongo-express:
    image: mongo-express
    env_file: .env
    container_name: newHackers_mongo_express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:${MONGODB_PORT}/
    depends_on:
      - mongodb
  app:
    container_name: App
    build: .
    restart: always
    env_file: .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongodb